# docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # environment:
    #   DATABASE_URL: "postgresql://user:password@db:5432/app_db"
    # depends_on:
    #   - db

  # db:
    # image: postgres:14
    # environment:
    #   POSTGRES_USER: user
    #   POSTGRES_PASSWORD: password
    #   POSTGRES_DB: app_db
    # volumes:
    #   - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:
#     driver: local